### ISSUE TITLE
system

### ISSUE THREAD

**Issue by TOM1457998914** [Z3NTL3/Anti-Cursed-Darkness-Squad-BETA#1]
Does it support centos? or only supports ubuntu system

**Comment by TOM1457998914** [comment]
python3: can't open file 'darkness.py': [Errno 2] No such file or directory

**Comment by TOM1457998914** [comment]
python3 darkness   
  File "darkness", line 1
SyntaxError: Non-UTF-8 code starting with '\xe8' in file darkness on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by Z3NTL3** [comment]
> Does it support centos? or only supports ubuntu system

It does not support CentOS. It will work finely on Ubuntu 18.04. Don't forget to execute the sudo apt update command first!
