### ISSUE TITLE
Sugestion

### ISSUE THREAD

**Issue by andress134** [Z3NTL3/Anti-Cursed-Darkness-Squad-BETA#13]
I notice that you really like working on dos / ddos projects
I would have a suggestion
Creating a new '' bypass-ip '' method or something
Create a function that uses the following script https://github.com/MrH0wl/Cloudmare
1. start the first session, put the https://cf-target.com the first session send the cf-target.com to https://github.com/MrH0wl/Cloudmare  to solve IP, if detect real IP in header
2. starting session 2, found the real ip from https://cf-target.com  and replace the https://cf-target.com with http://ip/
3. done, now hiting the real ip

**Comment by empfaked** [comment]
> 
> 
> I notice that you really like working on dos / ddos projects
> I would have a suggestion
> Creating a new '' bypass-ip '' method or something
> Create a function that uses the following script https://github.com/MrH0wl/Cloudmare
> 
>     1. start the first session, put the https://cf-target.com the first session send the cf-target.com to https://github.com/MrH0wl/Cloudmare  to solve IP, if detect real IP in header
> 
>     2. starting session 2, found the real ip from https://cf-target.com  and replace the https://cf-target.com with http://ip/
> 
>     3. done, now hiting the real ip

this tool dont work

**Comment by andress134** [comment]
> > I notice that you really like working on dos / ddos projects
> > I would have a suggestion
> > Creating a new '' bypass-ip '' method or something
> > Create a function that uses the following script https://github.com/MrH0wl/Cloudmare
> > ```
> > 1. start the first session, put the https://cf-target.com the first session send the cf-target.com to https://github.com/MrH0wl/Cloudmare  to solve IP, if detect real IP in header
> > 
> > 2. starting session 2, found the real ip from https://cf-target.com  and replace the https://cf-target.com with http://ip/
> > 
> > 3. done, now hiting the real ip
> > ```
> 
> this tool dont work

working, testing by me.
Rlly can't found all ips but rate is good  60/40

**Comment by empfaked** [comment]
> 
> 
> > > I notice that you really like working on dos / ddos projects
> > > I would have a suggestion
> > > Creating a new '' bypass-ip '' method or something
> > > Create a function that uses the following script https://github.com/MrH0wl/Cloudmare
> > > ```
> > > 1. start the first session, put the https://cf-target.com the first session send the cf-target.com to https://github.com/MrH0wl/Cloudmare  to solve IP, if detect real IP in header
> > > 
> > > 2. starting session 2, found the real ip from https://cf-target.com  and replace the https://cf-target.com with http://ip/
> > > 
> > > 3. done, now hiting the real ip
> > > ```
> > 
> > 
> > this tool dont work
> 
> working, testing by me.
> Rlly can't found all ips but rate is good 60/40

im tested 5 website dont work bro
