### ISSUE TITLE
After the update all attacks dosen't work.

### ISSUE THREAD

**Issue by Keasik** [Z3NTL3/Anti-Cursed-Darkness-Squad-BETA#14]
After the update all attacks dosen't work. Nc-Killer dosent hit too, but displays attack messages on the screen. Please, fix it.

**Comment by empfaked** [comment]
> After the update all attacks dosen't work. Nc-Killer dosent hit too, but displays attack messages on the screen. Please, fix it.

why did you decide that the attacks don't work?

**Comment by empfaked** [comment]
> 
> 
> After the update all attacks dosen't work. Nc-Killer dosent hit too, but displays attack messages on the screen. Please, fix it.

run ./fixer or reinstall darkness

**Comment by Z3NTL3** [comment]
> After the update all attacks dosen't work. Nc-Killer dosent hit too, but displays attack messages on the screen. Please, fix it.

Run one more time update command to get newer version and also type fixer in the menu to fix your software
