### ISSUE TITLE
Stealing code

### ISSUE THREAD

**Issue by scaredos** [Z3NTL3/Anti-Cursed-Darkness-Squad-BETA#17]
Half of the code in this repository is not yours, and you have provided no credit to the actual owners and developers.

**Comment by Z3NTL3** [comment]
Hello my stupid guy:

IN THE README FILE IT SAYS:
Thanks to MHProDev, R00tS3c, emp001 and wachirachoomsiri for their methods. This tool is an one-in-all DDOS Panel with the best methods. Only the panel it self, Turkish network blocker, the proxy-crawler and attack api logger discord webhooks is coded by z3ntl3 root. Others are not part of our code!

Also in the panel it says method devs and their credits so you re the most stupid guy i ever seen

**Comment by scaredos** [comment]
This is incorrect, your code uses methods developed by other people for usage inside of a program known as http-engine.

**Comment by Z3NTL3** [comment]
![image](https://user-images.githubusercontent.com/48758770/124393002-a39e6900-dcf8-11eb-8a54-3a737501d94d.png)

I never said that i have developed the code wtf u talking i have already mentioned the method developers, learn what a panel means

**Comment by Z3NTL3** [comment]
You need to learn reading first the readme and then you need to buy big glasses i guess to see good that i've credited all the method developers

**Comment by scaredos** [comment]
You have not credited all the owners.

**Comment by Z3NTL3** [comment]
Who have I forgotten?

**Comment by scaredos** [comment]
You have forgotten me and SLAVIC.

**Comment by Z3NTL3** [comment]
Can you prove it? Or send your repo of that method so i can see. Then i will credit u to, sorry if i did forget u really
