### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by nqkuftam** [Z3NTL3/Anti-Cursed-Darkness-Squad-BETA#2]
Hello! I have issue. I am on Ubuntu 18.04, I executed apt update&&upgrade and still not working.
When I execute the program ./darkness, go to random method and write the site and time it does not begin.
![image_2021-05-05_170315](https://user-images.githubusercontent.com/52350586/117153570-c88f6200-adc3-11eb-9a3f-f8ef4c3cc050.png)

**Comment by Z3NTL3** [comment]
You have to press one more time enter to make it start attack

**Comment by Z3NTL3** [comment]
This problem has been solved!

https://github.com/Z3NTL3/Anti-Cursed-Darkness-Squad-BETA/releases/tag/3.0
