### ISSUE TITLE
sudo: ./darkness: command not found

### ISSUE THREAD

**Issue by Egida** [Z3NTL3/Anti-Cursed-Darkness-Squad-BETA#20]
After the first launch, it does not want to run the script in the future

**Comment by Z3NTL3** [comment]
It means you do not have root access on your vps

**Comment by Egida** [comment]
There is root access, but I write that the first time the commands work, and after the end of the session, darkness disappears

**Comment by Z3NTL3** [comment]
Try:

chmod +x darkness
sudo ./darkness

**Comment by Z3NTL3** [comment]
After that done and worked then  see https://scorpion-hackz.com/acds/update-log.txt to update your panel. We have added a very nice rgb design
