### ISSUE TITLE
Putty Login To Net?

### ISSUE THREAD

**Issue by Wakandaf** [Z3NTL3/Anti-Cursed-Darkness-Squad-BETA#23]
if there is a way i can access this through putty pls let me know and don't delete my message pls :/

**Comment by Z3NTL3** [comment]
This is not a botnet bro. You need to effort a vps for your self your own.

**Comment by Wakandaf** [comment]
what vps do you recommend

**Comment by Z3NTL3** [comment]
16-32gb ram , 4-24 core or more , 2- 3 gbps or more
