### ISSUE TITLE
Can we run in Mobile

### ISSUE THREAD

**Issue by Haxcodertm** [Z3NTL3/Anti-Cursed-Darkness-Squad-BETA#26]
I was wondering if you can run this tool on mobile phone?

**Comment by Wakandaf** [comment]
yes you have to install termux or go to console.cloud.google.com them do all the install commands there

**Comment by oqvh** [comment]
how do i do it on windows? or can i not?

**Comment by Z3NTL3** [comment]
> I was wondering if you can run this tool on mobile phone?

Ye but you need a VPS, after that you can connect vi a JuiceSSH. Termux will not work btw

**Comment by Z3NTL3** [comment]
> how do i do it on windows? or can i not?

You can, but if your internet is lower than 1.2 GBPS and if your PC has bad ram and core then don't. Do it on VPS.
