### ISSUE TITLE
A problem !

### ISSUE THREAD

**Issue by sahraoui741** [Z3NTL3/Anti-Cursed-Darkness-Squad-BETA#3]
Hi there i had this problem 
can u help me guys ?
when i git clone then 
i typed like u said 
chmod +x darkness
then ./darkness
but it says 
[23514] Error loading Python lib '/tmp/_MEI3rEhAK/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEI3rEhAK/libpython3.8.so.1.0)

**Comment by Z3NTL3** [comment]
> Hi there i had this problem
> can u help me guys ?
> when i git clone then
> i typed like u said
> chmod +x darkness
> then ./darkness
> but it says
> [23514] Error loading Python lib '/tmp/_MEI3rEhAK/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEI3rEhAK/libpython3.8.so.1.0)

Hey,
I also noticed that problem yesterday. The problem is because I made an exe file via windows instead of linux.
At the end of this wonderful week, I will fix this problem. At the end of this week because of my exam.

Kinds regards

**Comment by Z3NTL3** [comment]
This problem has been solved!

https://github.com/Z3NTL3/Anti-Cursed-Darkness-Squad-BETA/releases/tag/3.0
