### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by Amedex** [Z3NTL3/Anti-Cursed-Darkness-Squad-BETA#30]
Why don't you give the source code of the script?

**Comment by Z3NTL3** [comment]
First. If you look at the Forks you will see that an old version already included a .py source.

Because of a few people who irritate me and because I don't want people to steal panel design and method-combiner trick, I removed that source again.

And I don't think you should care whether I post the source or not, that's none of your business.

**Comment by 0x0403** [comment]
> First. If you look at the Forks you will see that an old version already included a .py source.
> 
> Because of a few people who irritate me and because I don't want people to steal panel design and the method-combiner func, I removed that source again.
> 
> And I don't think you should care whether I post the source or not, that's none of your business.

thats a stupid fucking answer u retard fuck its clearly a fucking virus lmao

**Comment by Z3NTL3** [comment]
> > First. If you look at the Forks you will see that an old version already included a .py source.
> > Because of a few people who irritate me and because I don't want people to steal panel design and the method-combiner func, I removed that source again.
> > And I don't think you should care whether I post the source or not, that's none of your business.
> 
> thats a stupid fucking answer u retard fuck its clearly a fucking virus lmao

Imagine calling something a virus while it is not a virus 😂 You guys are big skids. Just stfu and dont use if you think its a virus. Dont be to much jealous :)

**Comment by 0x0403** [comment]
> > > First. If you look at the Forks you will see that an old version already included a .py source.
> > > Because of a few people who irritate me and because I don't want people to steal panel design and the method-combiner func, I removed that source again.
> > > And I don't think you should care whether I post the source or not, that's none of your business.
> > 
> > 
> > thats a stupid fucking answer u retard fuck its clearly a fucking virus lmao
> 
> Imagine calling something a virus while it is not a virus 😂 You guys are big skids. Just stfu and dont use if you think its a virus. Dont be to much jealous :)
> 
> Your calling it virus because the zip is auto blocked on windows security? 😂 Cheat engine is also blocked so is that a virus tho? 😂😂😂😂

"skids" half his fucking "ddos" attack code is pasted off public open source repos for security testing and the other half is skidded off discord retards who make perl scripts and the rat/whatever the fuck the virus is was probably also pasted off github

**Comment by 0x0403** [comment]
> > > First. If you look at the Forks you will see that an old version already included a .py source.
> > > Because of a few people who irritate me and because I don't want people to steal panel design and the method-combiner func, I removed that source again.
> > > And I don't think you should care whether I post the source or not, that's none of your business.
> > 
> > 
> > thats a stupid fucking answer u retard fuck its clearly a fucking virus lmao
> 
> Imagine calling something a virus while it is not a virus 😂 You guys are big skids. Just stfu and dont use if you think its a virus. Dont be to much jealous :)
> 
> Your calling it virus because the zip is auto blocked on windows security? 😂 Cheat engine is also blocked so is that a virus tho? 😂😂😂😂

not to mention this shit has literally never worked and wont even send a single packet or request for every single method youve ever added

**Comment by Z3NTL3** [comment]
> > > > First. If you look at the Forks you will see that an old version already included a .py source.
> > > > Because of a few people who irritate me and because I don't want people to steal panel design and the method-combiner func, I removed that source again.
> > > > And I don't think you should care whether I post the source or not, that's none of your business.
> > > 
> > > 
> > > thats a stupid fucking answer u retard fuck its clearly a fucking virus lmao
> > 
> > 
> > Imagine calling something a virus while it is not a virus 😂 You guys are big skids. Just stfu and dont use if you think its a virus. Dont be to much jealous :)
> > Your calling it virus because the zip is auto blocked on windows security? 😂 Cheat engine is also blocked so is that a virus tho? 😂😂😂😂
> 
> "skids" half his fucking "ddos" attack code is pasted off public open source repos for security testing and the other half is skidded off discord retards who make perl scripts and the rat/whatever the fuck the virus is was probably also pasted off github

In the readme it literally said:
Powerful Layer 7 & 4 panel.

Thanks to MHProDev, Leeon123, R00tS3c, emp001, cocorisss and wachirachoomsiri for their methods. This tool is an one-in-all DDOS Panel with the best methods. Only the panel it self, functionality, the proxy-crawler is coded by z3ntl3 root. Others are not part of our code!

NOTICE: When proxies banned, then renew it by "proxy-crawl" command.


We are not responsable for what u do with this tool.

Also when you type developers in the panel, all method developers were mentioned. You cant even code one single line, skid. The panel have a lot users and your so jealous😂

**Comment by Amedex** [comment]
Woooow, just some pasted shit of proxy scrapers and a bunch of mass pasted shit from multiple sources, you wven "made" a web shell creator, with just does a wget to get the php wso shell.... So gorgeous..

**Comment by Z3NTL3** [comment]
> Woooow, just some pasted shit of proxy scrapers and a bunch of mass pasted shit from multiple sources, you wven "made" a web shell creator, with just does a wget to get the php wso shell.... So gorgeous..

Literally i didnt paste any code  everything is coded by me only the ddos files like websiter nuker js and so on are not mine methods, already credited the people. Your a verh shitty skid

**Comment by Z3NTL3** [comment]
> Woooow, just some pasted shit of proxy scrapers and a bunch of mass pasted shit from multiple sources, you wven "made" a web shell creator, with just does a wget to get the php wso shell.... So gorgeous..


Your talking about wp bot?😂 
https://github.com/Z3NTL3/SkidTracer
https://github.com/Z3NTL3/Scorpy-Proxies

**Comment by 0x0403** [comment]
> > Woooow, just some pasted shit of proxy scrapers and a bunch of mass pasted shit from multiple sources, you wven "made" a web shell creator, with just does a wget to get the php wso shell.... So gorgeous..
> 
> Your talking about shellgen, that was literally 1.2 years ago and my first ever python code. Why you ignore the good ones, ma skid😂?😂
> https://github.com/Z3NTL3/SkidTracer
> https://github.com/Z3NTL3/Scorpy-Proxies

fucking retard skid you havnt coded shit ive been a full stack developer for 7 years lmao and ive been a professional penetration tester on a red team for 5 so far nearly 6 years its not just the proxies even without proxies it cant send a single packet i was monitoring with a packet sniffer on a private server

**Comment by Z3NTL3** [comment]
> > > Woooow, just some pasted shit of proxy scrapers and a bunch of mass pasted shit from multiple sources, you wven "made" a web shell creator, with just does a wget to get the php wso shell.... So gorgeous..
> > 
> > 
> > Your talking about shellgen, that was literally 1.2 years ago and my first ever python code. Why you ignore the good ones, ma skid😂?😂
> > https://github.com/Z3NTL3/SkidTracer
> > https://github.com/Z3NTL3/Scorpy-Proxies
> 
> fucking retard skid you havnt coded shit ive been a full stack developer for 7 years lmao and ive been a professional penetration tester on a red team for 5 so far nearly 6 years its not just the proxies even without proxies it cant send a single packet i was monitoring with a packet sniffer on a private server

Look ar ur github 0 stars. Your the biggest lamer ive ever seen. u think that i cant code ? How did i made a panel, skid tracer and such other projects? This is the first every python panel so far wtf u talking. u cant even code one single line.

**Comment by Haxcodertm** [comment]
> > > Woooow, just some pasted shit of proxy scrapers and a bunch of mass pasted shit from multiple sources, you wven "made" a web shell creator, with just does a wget to get the php wso shell.... So gorgeous..
> > 
> > 
> > Your talking about shellgen, that was literally 1.2 years ago and my first ever python code. Why you ignore the good ones, ma skid😂?😂
> > https://github.com/Z3NTL3/SkidTracer
> > https://github.com/Z3NTL3/Scorpy-Proxies
> 
> fucking retard skid you havnt coded shit ive been a full stack developer for 7 years lmao and ive been a professional penetration tester on a red team for 5 so far nearly 6 years its not just the proxies even without proxies it cant send a single packet i was monitoring with a packet sniffer on a private server

Why are you mad if he don't want to give his source code you mother fucker piece of shit.  We all know that you want to take advantage to copy his code and claim it as yours.. right? You dumb ass skids.  Code it by your self.  

Getting angry for the things that others owned, shame on you. You're just jealous because you don't have one.

**Comment by Z3NTL3** [comment]
> > > > Woooow, just some pasted shit of proxy scrapers and a bunch of mass pasted shit from multiple sources, you wven "made" a web shell creator, with just does a wget to get the php wso shell.... So gorgeous..
> > > 
> > > 
> > > Your talking about shellgen, that was literally 1.2 years ago and my first ever python code. Why you ignore the good ones, ma skid😂?😂
> > > https://github.com/Z3NTL3/SkidTracer
> > > https://github.com/Z3NTL3/Scorpy-Proxies
> > 
> > 
> > fucking retard skid you havnt coded shit ive been a full stack developer for 7 years lmao and ive been a professional penetration tester on a red team for 5 so far nearly 6 years its not just the proxies even without proxies it cant send a single packet i was monitoring with a packet sniffer on a private server
> 
> Why are you mad if he don't want to give his source code you mother fucker piece of shit. We all know that you want to take advantage to copy his code and claim it as yours.. right? You dumb ass skids. Code it by your self.
> 
> Getting angry for the things that others owned, shame on you. You're just jealous because you don't have one.

Exactly  ❤

**Comment by 0x0403** [comment]
> > > > Woooow, just some pasted shit of proxy scrapers and a bunch of mass pasted shit from multiple sources, you wven "made" a web shell creator, with just does a wget to get the php wso shell.... So gorgeous..
> > > 
> > > 
> > > Your talking about shellgen, that was literally 1.2 years ago and my first ever python code. Why you ignore the good ones, ma skid😂?😂
> > > https://github.com/Z3NTL3/SkidTracer
> > > https://github.com/Z3NTL3/Scorpy-Proxies
> > 
> > 
> > fucking retard skid you havnt coded shit ive been a full stack developer for 7 years lmao and ive been a professional penetration tester on a red team for 5 so far nearly 6 years its not just the proxies even without proxies it cant send a single packet i was monitoring with a packet sniffer on a private server
> 
> Look ar ur github 0 stars. Your the biggest lamer ive ever seen. u think that i cant code ? How did i made a panel, skid tracer and such other projects? This is the first every python panel so far wtf u talking. u cant even code one single line.

fucking retard this is an alt account not my actual github i would never say the shit im saying on my company github
