### ISSUE TITLE
its not work 

### ISSUE THREAD

**Issue by ZzeusS-cyber** [Z3NTL3/Anti-Cursed-Darkness-Squad-BETA#33]
Z3NTL3
/
Anti-Cursed-Darkness-Squad-BETA 

its not work in API  2 problem can you fixed

**Comment by Z3NTL3** [comment]
> Z3NTL3
> /
> Anti-Cursed-Darkness-Squad-BETA
> 
> its not work in API 2 problem can you fixed

One of the Proxy API is down. In order to fix, i need my computer. But i'm ar vacation. I return on 28 aug.

I contacted also the API provider, they have a problem in their backend. They try to fix it. Maybe 1-7 day till they fix. If i had a pc at vacation, i would use new API, but cant cuz m at vacation.

You can follow when the panel is up via:
status.scorpion-hackz.com

**Comment by gov-sec** [comment]
doesnt work because its a rat with a bunch of random skidded scripts this child found on github thrown together in one big pile of no-ounce garbage

**Comment by Z3NTL3** [comment]
> doesnt work because its a rat with a bunch of random skidded scripts this child found on github thrown together in one big pile of no-ounce garbage

Hey skid, nice to see your review.

First of all, if you type developers into the panel, you'll see the method developers credited.

And also, without the method combiner feature we madw, your attacks of these methods are to low.

Its a fun part that you think this is a rat. With that you exposed yourself that you are a big little skid :)

Have a nice day

**Comment by gov-sec** [comment]
> > doesnt work because its a rat with a bunch of random skidded scripts this child found on github thrown together in one big pile of no-ounce garbage
> 
> Hey skid, nice to see your review.
> 
> First of all, if you type developers into the panel, you'll see the method developers credited.
> 
> And also, without the method combiner feature we madw, your attacks of these methods are to low.
> 
> Its a fun part that you think this is a rat. With that you exposed yourself that you are a big little skid :)
> 
> Have a nice day

cope harder retard
