### ISSUE TITLE
help

### ISSUE THREAD

**Issue by michael809-byte** [Z3NTL3/Anti-Cursed-Darkness-Squad-BETA#36]
when i run unzip Darkness.zip it asks me if i want to remove files. what option do i choose?

root@foo:/home/ubuntu/ddos# unzip Darkness.zip
Archive:  Darkness.zip
  inflating: httpflood
  inflating: HTTP-RAW.js
  inflating: installer.py
  inflating: method.js
  inflating: package.json
  inflating: privacypass.json
  inflating: proxies.txt
replace putty.png? [y]es, [n]o, [A]ll, [N]one, [r]ename:

**Comment by Z3NTL3** [comment]
you have to press y otherwise installer.py wont extracted and then you cant install the required modulee
