### ISSUE TITLE
Telnet/UDP error

### ISSUE THREAD

**Issue by Visible-Illusion** [Z3NTL3/Anti-Cursed-Darkness-Squad-BETA#6]
When I try to use the Telnet or UDP tools, it shows this error:

Setting up Sockets...
Could not open raw socket.

How can I fix this?

**Comment by Z3NTL3** [comment]
Hi,

We are also aware that there are problems with "telnet" & "udp". I will be releasing an update today replacing them with better private layer 4 scripts.

Thanks for your report.

**Comment by empfaked** [comment]
> When I try to use the Telnet or UDP tools, it shows this error:
> 
> Setting up Sockets...
> Could not open raw socket.
> 
> How can I fix this?


fix at the beginning to write sudo ./darkness

**Comment by sahraoui741** [comment]
please can u fix it !

**Comment by Z3NTL3** [comment]
I will.

**Comment by Z3NTL3** [comment]
> When I try to use the Telnet or UDP tools, it shows this error:
> 
> Setting up Sockets...
> Could not open raw socket.
> 
> How can I fix this?

In vps it will work
