### ISSUE TITLE
I just wanna say !

### ISSUE THREAD

**Issue by sahraoui741** [Z3NTL3/Anti-Cursed-Darkness-Squad-BETA#7]
There is no problem i found 
i just wanna thank you from my heart guys for hard working thank u and i will be with u and support u until the end !
Thank u <3

**Comment by Z3NTL3** [comment]
> There is no problem i found
> i just wanna thank you from my heart guys for hard working thank u and i will be with u and support u until the end !
> Thank u <3

These kinds of messages make us very happy. We are motivated by these kinds of messages.

Thanks!

**Comment by andress134** [comment]
> There is no problem i found
> i just wanna thank you from my heart guys for hard working thank u and i will be with u and support u until the end !
> Thank u <3

thanks for what ? haha, check the logs of your server /etc/passwd etc and say thanks again
This kid @Z3NTL3  just share some scripts that contain  backdoor, him can steal your server and mining with your server.
Today i tried this shit of scripts and see here are backdoor
I will post proof tonight when back home.

**Comment by Z3NTL3** [comment]
> > There is no problem i found
> > i just wanna thank you from my heart guys for hard working thank u and i will be with u and support u until the end !
> > Thank u <3
> 
> thanks for what ? haha, check the logs of your server /etc/passwd etc and say thanks again
> This kid @Z3NTL3 just share some scripts that contain backdoor, him can steal your server and mining with your server.
> Today i tried this shit of scripts and see here are backdoor
> I will post proof tonight when back home.

I think you need to go to the doctor :) Biggest cap but i respect your comment thnx baby :)

**Comment by andress134** [comment]
> > > There is no problem i found
> > > i just wanna thank you from my heart guys for hard working thank u and i will be with u and support u until the end !
> > > Thank u <3
> > 
> > 
> > thanks for what ? haha, check the logs of your server /etc/passwd etc and say thanks again
> > This kid @Z3NTL3 just share some scripts that contain backdoor, him can steal your server and mining with your server.
> > Today i tried this shit of scripts and see here are backdoor
> > I will post proof tonight when back home.
> 
> I think you need to go to the doctor :) Biggest cap but i respect your comment thnx baby :)

Next time lear to obuscate the code again (using he obuscator .io online the code can be visible easy), if u compile the script use other libs if want to can;t reverse, make sure u disable all type of debug (if u dont want to be visible the logs created by your backdoor)
1. No one are u script or made by you, all type of scripts are public and already leaked many times.
2. Do u use a public scripts to share your backdoor
3. .Yeah, 'will go to the doctor' lets see, just wait me some hours to come home and will share the proof with your backdoor

**Comment by Z3NTL3** [comment]
> > > > There is no problem i found
> > > > i just wanna thank you from my heart guys for hard working thank u and i will be with u and support u until the end !
> > > > Thank u <3
> > > 
> > > 
> > > thanks for what ? haha, check the logs of your server /etc/passwd etc and say thanks again
> > > This kid @Z3NTL3 just share some scripts that contain backdoor, him can steal your server and mining with your server.
> > > Today i tried this shit of scripts and see here are backdoor
> > > I will post proof tonight when back home.
> > 
> > 
> > I think you need to go to the doctor :) Biggest cap but i respect your comment thnx baby :)
> 
> Next time lear to obuscate the code again (using he obuscator .io online the code can be visible easy), if u compile the script use other libs if want to can;t reverse, make sure u disable all type of debug (if u dont want to be visible the logs created by your backdoor)
> 
> 1. No one are u script or made by you, all type of scripts are public and already leaked many times.
> 2. Do u use a public scripts to share your backdoor
> 3. .Yeah, 'will go to the doctor' lets see, just wait me some hours to come home and will share the proof with your backdoor

Bruh, its not even obfuscated thats one. Two is i already mentioned that this is an ddos panel with the best scripts and method developers are already wroten. I just coded the panel and proxy crawler. I mentioned this already in my readme.md. Also the method developers even starred this project.

Your a fucking skid a retard. Just stfu. Learn to call when something has a backdoor. This does not even have a backdoor fucking kid.

**Comment by Z3NTL3** [comment]
![image](https://user-images.githubusercontent.com/48758770/120643725-cd087280-c476-11eb-93ed-05b451b8be50.png)

i recommend you to go to the doctor.

**Comment by andress134** [comment]
all these scripts were written by user Node#6354 after which he saw a user's scripts and kasper stole and posted them publicly.
There is nothing made by you or made by rootsec or other users, that users just copied and edit some lines, there are some scriptures from 1 year and 4 months ago, very old scriptures

Why u obuscate the code ?

```
js
cf.request({
        'method': randommethod,
        'resolveWithFullResponse': true,
        'headers': {
            'User-Agent': random_useragent.getRandom(),
            'Referer': target,
            'Connection': 'Keep-Alive',
            'Keep-Alive': 'timeout=10, max=100',
            'X-Forwarded-For': randomNumber(1, 255) + '.' + randomNumber(1, 255) + '.' + randomNumber(1, 255) + '.' + randomNumber(1, 255)
        },
        'uri': target + '?' etc etc etc (other code)
```
If u share some scripts (the compiled) do not share backdoor, or if the scripts are not your, check first time don't post  to infect all users

**Comment by Z3NTL3** [comment]
I did not even share backdoor what u talkin about

**Comment by Z3NTL3** [comment]
And i can't know which person is the real coder of these scripts. I just develop the panel and proxy crawler and putt the best scripts i found.
