### ISSUE TITLE
Thanks 

### ISSUE THREAD

**Issue by empfaked** [Z3NTL3/Anti-Cursed-Darkness-Squad-BETA#9]
This project is very good, update it often please ))
add something new, advertise vidos on YouTube

**Comment by xLiquidd** [comment]
How did you activate it? could you contact me?

**Comment by xLiquidd** [comment]
Discord: M4ks4t#8814

**Comment by xLiquidd** [comment]
i have done ok

**Comment by empfaked** [comment]
> How did you activate it? could you contact me?

what problem ? what error?

**Comment by Z3NTL3** [comment]
> This project is very good, update it often please ))
> add something new, advertise vidos on YouTube

Thanks <3
